#!/usr/bin/env bash

set -Eeuo pipefail

##
## Builds the three docker images we use in CI.
##

# Two of the images are builds for specific OS:s. The third is a lightweight
# container just used to run a shell script. Honestly, it's kind of overkill.
#
# Build Systems
#
# 1. Ubuntu 14.04 LTS, for our extremely ancient production system still in use
#    as of 2020-05-04.
# 2. Centos 7, for the new production system that will be hosted on OSUOSL (but
#    doesn't exist yet.)
#
# Technically, we're only interested in different versions of libc, I think, but
# I am not interested in optimizing that right now. Choosing OS is sufficient.

# Image sources are directories. NOTE! The directory names are modified to create
# image names and variable names below.
image_sources=(
    image-build-ubuntu-14.04
    image-build-centos-7
    image-deploy
)

# Used in creating image names.
name_prefix=snowdriftcoop/snowdrift-ci-

hdr () {
    echo
    echo "## $@"
    echo
}

cd $(dirname $0)

new_images=$(mktemp)
trap "rm -f $new_images" ERR

cat > $new_images <<EOF
# GENERATED BY build-docker-images.sh ON $(date -Id).
#
# EDIT AT YOUR OWN PERIL.
#
# This file is included by the top-level .gitlab-ci.yml.
variables:
EOF

for src in "${image_sources[@]}"; do (
    cd docker/$src

    # Convert src directory to image name
    image_name=${name_prefix}${src#image-}

    hdr Building $image_name

    # Extract short image id:
    #
    # sha256:947c9348a2dbccd52a...
    # _______^^^^^^^^^^^^______...
    image_id=$(docker build -q . | cut -b 8-19)

    image=${image_name}:${image_id}

    echo Built image $image

    hdr "Tagging and pushing $image"

    docker tag $image_id $image
    # This is a local developer convenience.
    docker tag $image_id ${image_name}:latest
    docker push $image

    # Convert src directory to variable name
    echo -n "  \"$src\": " | sed -e 's/\./_/g' -e 's/-/_/g' >> $new_images
    docker image inspect $image | jq '.[].RepoDigests[0]' >> $new_images

) done

hdr "All Done"

mv $new_images docker/images.yml
git diff docker/images.yml

if ! git diff --exit-code  --quiet docker/images.yml
then
    hdr "Don't forget to commit these changes!"
fi
