#!/usr/bin/env bash
set -Eeuo pipefail

DEBUG=false
DEBUG=${KETER_DEBUG+true}

if $DEBUG; then set -x; fi

#
# keter.sh: Like "yesod keter", but works with our split-package project.
#

#
# Options
#

opt_build=${BUILD:=true}
opt_deploy=${DEPLOY:=true}
# NB! Whatever name is used here must also be used in the 'crowdmatch' app
# (crowdmatch/app/crowdmatch.hs), where it is used to pull in postgres
# configuration. Must fix.
opt_appname=${APPNAME:=SnowdriftReboot}

#
#
#

install_path=./website/dist/bin

contents=(
    config
    static
    dist
)

export PGDATABASE=snowdrift_deploy


# Project-specific override
stack () {
    command stack ${SD_STACK_ARGS?-} "$@"
}

dbmake () {
    stack exec -- ${SD_PGUSER+sudo -u $SD_PGUSER} make -f db.makefile "$@"
}


hdr () {
    echo -e "\n-- $@"
}

main () {
    if $opt_build
    then
        hdr "Building"
        if [ -z "$install_path" ]; then
            >&2 echo "Hold up, \$install_path should be specified!"
            exit 1
        fi
        rm -rf ${install_path}
        mkdir -p ${install_path}
        stack clean
        # Have to do dependencies without --pedantic, since stack still
        # rebuilds extra-deps specified as git repos after a clean. :(
        # Refer to https://github.com/commercialhaskell/stack/issues/1295
        stack \
            build \
            --dependencies-only \
            --install-ghc
        (trap "dbmake stop" EXIT
        dbmake
        stack \
            --local-bin-path $install_path \
            install \
            --flag Snowdrift:-dev \
            --pedantic
        ) # dbmake stop
        hdr "Packing executables"
        find ${install_path} -type f -executable | xargs upx
        hdr "Tarballing"
        rm -rf website/static/tmp/*
        # This forces regeneration of the client session key, which will reset
        # everybody's sessions. This is a bug, but it's better than the current
        # behavior of using whatever key is on my system. :|
        # See https://tree.taiga.io/project/snowdrift/issue/401
        rm -f website/config/client_session_key.aes
        tar czf ${opt_appname}.keter -C website ${contents[@]}
    else
        hdr "Not building, as requested"
    fi
    if $opt_deploy
    then
        hdr "Deploying"
        (
            keyfile=$(mktemp)
            host_keyfile=$(mktemp)
            trap "rm -f $keyfile $host_keyfile" EXIT
            chmod 600 $keyfile

            # Turn off -x to dump secrets
            if $DEBUG; then set +x; fi
            echo "$PROD_SSH_KEY" > $keyfile
            echo "$PROD_HOST_KEY" > $host_keyfile
            # Turn it back on
            if $DEBUG; then
                wc $keyfile $host_keyfile
                set -x
            fi

            scp -i $keyfile \
                -o "UserKnownHostsFile $host_keyfile" \
                ${opt_appname}.keter \
                gitlab@${SD_MAIN_INSTANCE_IP}:/opt/keter/incoming
        )
    else
        hdr "Not deploying, as requested"
    fi
}

time main
