#!/usr/bin/env bash
set -Eeuo pipefail

#
# keter.sh: Like "yesod keter", but works with our split-package project.
#

#
# Options
#

opt_debug=${KETER_DEBUG:-false}
opt_build=${BUILD:-true}
opt_deploy=${DEPLOY:-true}
# Assume the DB is already available
opt_setup_db=${SETUP_DB:-false}

# NB! Whatever name is used here must also be used in the 'crowdmatch' app
# (crowdmatch/app/crowdmatch.hs), where it is used to pull in postgres
# configuration. Must fix.
opt_appname=${APPNAME:-SnowdriftReboot}

#
#
#

if $opt_debug; then set -x; fi

install_path=./website/dist/bin

contents=(
    config
    static
    dist
)

if $opt_setup_db; then
    export PGDATABASE=snowdrift_deploy
fi


# Project-specific override
stack () {
    command stack ${SD_STACK_ARGS?-} "$@"
}

dbmake () {
    if $opt_setup_db; then
        stack exec -- make -f db.makefile "$@"
    else
        echo "Skipping DB step"
    fi
}


hdr () {
    echo -e "\n-- $@"
}

main () {
    if $opt_build
    then
        hdr "Building"
        if [ -z "$install_path" ]; then
            >&2 echo "Hold up, \$install_path should be specified!"
            exit 1
        fi
        rm -rf ${install_path}
        mkdir -p ${install_path}
        stack clean
        # Have to do dependencies without --pedantic, since stack still
        # rebuilds extra-deps specified as git repos after a clean. :(
        # Refer to https://github.com/commercialhaskell/stack/issues/1295
        stack \
            build \
            --dependencies-only \
            --install-ghc
        (trap "dbmake stop" EXIT
        dbmake
        stack \
            --local-bin-path $install_path \
            install --test \
            --flag Snowdrift:-dev \
            --pedantic
        ) # dbmake stop

        hdr "Tarballing"
        rm -rf website/static/tmp/*
        # This forces regeneration of the client session key, which will reset
        # everybody's sessions. This is a bug, but it's better than the current
        # behavior of using whatever key is on my system. :|
        # See https://tree.taiga.io/project/snowdrift/issue/401
        rm -f website/config/client_session_key.aes

        tar czf ${opt_appname}.keter -C website ${contents[@]}
    else
        hdr "Not building, as requested"
    fi
    if $opt_deploy
    then
        hdr "Deploying"
        # This uses GitLab's "variable is a temp file" feature.
        keyfile="$PROD_SSH_KEY"
        host_keyfile="$PROD_HOST_KEY"

        # SSH doesn't know our environment is already read-only. Well, better to
        # say, SSH wisely doesn't trust that our environment is read-only,
        # because that sort of depends on a lot of things. Here's the facts,
        # though: I am just as likely to screw this up as GitLab are, so I'll
        # just live with this.
        chmod 600 $keyfile

        scp -i $keyfile \
            -o "UserKnownHostsFile $host_keyfile" \
            ${opt_appname}.keter \
            gitlab@${SD_MAIN_INSTANCE_IP}:/opt/keter/incoming
    else
        hdr "Not deploying, as requested"
    fi
}

time main
