stanzas:
    - type: webapp
      hosts:
          - snowdrift.coop
          - www.snowdrift.coop
      exec: ../dist/bin/Snowdrift
      args: []
      env:
          APPROOT: https://snowdrift.coop
          SD_EMAILS: "true"
plugins:
    postgres: true
