((haskell-mode . ((haskell-indentation-layout-offset . 4)
                  (haskell-indentation-starter-offset . 1)
                  (haskell-indentation-left-offset . 4)
                  (haskell-indentation-ifte-offset . 4)
                  (haskell-indentation-where-pre-offset . 2)
                  (haskell-indentation-where-post-offset . 2)
                  (evil-shift-width . 2)
                  (haskell-tags-on-save . t)))
 (hamlet-mode . ((hamlet/basic-offset . 4))))
