#!/bin/sh
#
# Note: as of 2016-05-15, this works on the site currently up on
# <https://snowdrift.coop>. This *will not* work on the new site.

curl -sL 'https://snowdrift.coop/dev/build' |
    sed 's,^.\+<title>\([0-9a-fA-F]\{40\}\)</title>.\+$,\1,' |
    head -1
