flags:
  Snowdrift:
    dev: true
resolver: lts-8.24
packages:
  - website
  - crowdmatch
  - run-persist
  # This is patched to use UTCTime instead of Localtime (needs to get moved
  # upstream: see https://git.snowdrift.coop/sd/snowdrift/issues/8)
  - location:
     git: https://git.snowdrift.coop/sd/postgresql-simple-migration-patches.git
     commit: 55ae21a7ee5b0386ec7c6909409b1bdacebcc924
    extra-dep: true
extra-deps:
  - hashids-1.0.2.3
  - libravatar-0.4
  # Version in lts-8 is still old and bad
  - tasty-discover-3.0.2
  # Upsert is fixed in 2.7, which is not in lts-8
  - persistent-2.7.0
nix:
  pure: false
  packages:
    - ncurses
    - gmp
    - gcc
    - openssl
    - postgresql
    - zlib
