flags:
  Snowdrift:
    dev: true
resolver: snapshot.yaml
packages:
  - website
  - crowdmatch
  - run-persist
nix:
  pure: false
  packages:
    - ncurses
    - gmp
    - gcc
    - openssl
    - postgresql96
    - zlib
    - gnumake
