flags:
  Snowdrift:
    dev: true
resolver: lts-9.18
packages:
  - website
  - crowdmatch
  - run-persist
extra-deps:
  - hashids-1.0.2.3
  - hsass-0.5.0
  # Stripe is absent from lts-9
  - stripe-core-2.2.3
  - stripe-haskell-2.2.3
  - stripe-http-streams-2.2.3
  # This is patched to use UTCTime instead of Localtime (needs to get moved
  # upstream: see https://gitlab.com/snowdrift/snowdrift/issues/8)
  - git: https://gitlab.com/snowdrift/postgresql-simple-migration-patches.git
    commit: 55ae21a7ee5b0386ec7c6909409b1bdacebcc924
  - git: https://notabug.org/fr33domlover/shakespeare-sass.git
    commit: e25b7f6699096e0ffa619dc71a8ef028940e5bb9
  # Please remove this and edit dev-tools/tag.sh once v0.5.1.3 comes out.
  # We'll then just do `stack install codex`.
  - git: https://github.com/aloiscochard/codex.git
    commit: 0d59fe5099136015912e13a4c1ea573c5fd7f2ff
nix:
  pure: false
  packages:
    - ncurses
    - gmp
    - gcc
    - openssl
    - postgresql96
    - zlib
    - gnumake
