flags: {}
packages:
- '.'
extra-deps:
# Absent from LTS 2.13
- mime-0.4.0.2
- github-0.13.2
- titlecase-0.1.0.1
- yesod-markdown-0.9.4
# Transitive dep of github
- failure-0.2.0.3
# Constrained to different version by cabal file
- yesod-test-1.4.2.2
resolver: lts-2.13
