Widget users@Int64 share_value@Milray project_value@Milray: #{show users} #{plural users "person is" "people are"} pledging #{show share_value}/share for a total of #{show project_value}/month to this project.
Members users@Int64: #{show users} #{plural users "member" "members"}
Patrons users@Int64: #{show users} #{plural users "patron" "patrons"}
Shares shares@Int64: #{show shares} #{plural shares "share" "shares"}
NewMessages messages@Int: #{show messages} New #{plural messages "Message" "Messages"}
NewApplications applications@Int: #{show applications} New #{plural applications "Application" "Applications"}
NewComments comments@Int: #{show comments} New #{plural comments "Comment" "Comments"}
NewWikiEdits edits@Int: #{show edits} New #{plural edits "Wiki Edit" "Wiki Edits"}
