Hello: Hello
Widget users@Int64 share_value@Milray project_value@Milray: #{show users} #{plural users "person is" "people are"} contributing #{show share_value}/share for a total of #{show project_value}/month to this project.
Members users@Int64: #{show users} #{plural users "member" "members"}
Shares shares@Int64: #{show shares} #{plural shares "share" "shares"}
NewMessages messages@Int: #{show messages} New #{plural messages "Message" "Messages"}
NewApplications applications@Int: #{show applications} New #{plural applications "Application" "Applications"}
